service: serverless-step-function-app

plugins:
  - serverless-plugin-aws-alerts
  - serverless-step-functions

custom:
  alerts:
    stages:
      - dev
    topics:
      alarm:
        topic: ${self:provider.environment.SNS_TOPIC}
        notifications:
          - protocol: email
            endpoint: it199@hotmail.com 
    alarms:
      - functionErrors
      - functionThrottles

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev # Default stage to be used. Default is "dev"
  region: us-east-1 # Default region to be used. Default is "us-east-1"
  memorySize: 256
  timeout: 10

functions:
  hello:
    handler: index.handler

stepFunctions:
  stateMachines:
    snsExample:
      name: sns-example
      definition:
        Comment: Demonstrate how the SNS integration works
        StartAt: Publish SNS message
        States:
          Publish SNS message:
            Type: Task
            Resource: arn:aws:states:::sns:publish
            Parameters:
              Message: "{ \"answer\": 42 }"
              TopicArn:
                Ref: AlarmTopic
              MessageAttributes:
                foo:
                  DataType: String
                  StringValue: bar
            End: true
      alarms:
        topics:
          ok: 'arn:aws:sns:${opt:region, self:provider.region}:NotifyMe'
          alarm: 'arn:aws:sns:${opt:region, self:provider.region}:NotifyMe'
          insufficientData: 'arn:aws:sns:${opt:region, self:provider.region}:NotifyMe'
        metrics:
          - executionsTimeOut
          - executionsFailed
          - executionsAborted
          - executionThrottled

resources:
  Resources:
    AlarmTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: my-topic
        TopicName: my-topic